/**
 * Canonical exam validation (Sections 35–38).
 *
 * Every question generated by the AI is validated against the shared domain
 * model BEFORE it is persisted. Malformed output is rejected (the caller may
 * regenerate or surface a real error) — we never silently insert a partial or
 * invalid exam. Existing exam contracts in study.server.ts and
 * exam-engine.server.ts both normalise through these helpers so there is one
 * source of truth.
 */

export type ExamQuestionType = "mcq" | "truefalse" | "written";

export type ExamQuestion = {
  id: string;
  type: ExamQuestionType;
  question: string;
  options?: string[];
  answer: string;
  marks: number;
  difficulty?: string;
  chapter?: string;
  topic?: string;
  language?: string;
  explanation?: string;
};

export type ExamConfig = {
  difficulty: string;
  language: string;
  durationMinutes: number;
  negativeMarking: number;
  provider?: string;
  model?: string;
};

export class ExamValidationError extends Error {
  constructor(
    message: string,
    readonly details: string[],
  ) {
    super(message);
    this.name = "ExamValidationError";
  }
}

const VALID_TYPES: ExamQuestionType[] = ["mcq", "truefalse", "written"];

/** Normalise unknown AI output into a question list, or throw with reasons. */
export function validateExamQuestions(raw: unknown): ExamQuestion[] {
  const errors: string[] = [];
  if (!raw || typeof raw !== "object") {
    throw new ExamValidationError("AI returned no exam object.", ["response is not an object"]);
  }
  const q = (raw as { questions?: unknown }).questions;
  if (!Array.isArray(q) || q.length === 0) {
    throw new ExamValidationError("AI returned no questions.", ["questions array is empty"]);
  }

  const seenIds = new Set<string>();
  const out: ExamQuestion[] = [];

  q.forEach((item, idx) => {
    const here: string[] = [];
    if (!item || typeof item !== "object") {
      errors.push(`question ${idx + 1}: not an object`);
      return;
    }
    const r = item as Record<string, unknown>;
    const id = typeof r["id"] === "string" && r["id"].trim() ? r["id"].trim() : `q${idx + 1}`;
    if (seenIds.has(id)) here.push(`duplicate id "${id}"`);
    seenIds.add(id);

    const type = r["type"] as ExamQuestionType;
    if (!VALID_TYPES.includes(type)) here.push(`invalid type "${String(r["type"])}"`);

    const question = typeof r["question"] === "string" ? r["question"].trim() : "";
    if (question.length < 3) here.push("question text missing or too short");

    const answer = r["answer"];
    const answerStr = answer == null ? "" : String(answer).trim();
    if (!answerStr) here.push("answer is required");

    const marks = Number(r["marks"]);
    if (!Number.isFinite(marks) || marks <= 0) here.push("marks must be a positive number");

    if (type === "mcq") {
      const opts = Array.isArray(r["options"]) ? r["options"] : [];
      if (opts.length !== 4) here.push("MCQ must have exactly 4 options");
      else if (opts.some((o) => typeof o !== "string" || !o.trim()))
        here.push("MCQ options must be non-empty strings");
      else if (!opts.map((o: unknown) => String(o).trim()).includes(answerStr))
        here.push(`MCQ answer "${answerStr}" is not one of the options`);
    }
    if (type === "truefalse") {
      if (!/^(true|false)$/i.test(answerStr)) here.push("true/false answer must be True or False");
    }
    if (type === "written" && answerStr.length < 2) {
      here.push("written question needs a model answer");
    }

    if (here.length) {
      errors.push(`question ${idx + 1} (${id}): ${here.join("; ")}`);
      return;
    }
    out.push({
      id,
      type,
      question,
      ...(type === "mcq"
        ? { options: (r["options"] as unknown[]).map((o) => String(o).trim()) }
        : {}),
      answer: answerStr,
      marks,
      ...(typeof r["difficulty"] === "string" ? { difficulty: r["difficulty"] } : {}),
      ...(typeof r["chapter"] === "string" ? { chapter: r["chapter"] } : {}),
      ...(typeof r["topic"] === "string" ? { topic: r["topic"] } : {}),
      ...(typeof r["language"] === "string" ? { language: r["language"] } : {}),
      ...(typeof r["explanation"] === "string" ? { explanation: r["explanation"] } : {}),
    });
  });

  if (errors.length) {
    throw new ExamValidationError("Exam validation failed.", errors);
  }
  return out;
}

/**
 * Build a deterministic request id for an exam generation request so retrying
 * the same input does not create duplicate exams (Section 38). Id is a hash of
 * the guest + topic + counts + difficulty + language, stable across retries.
 */
export function examRequestId(input: {
  guestId: string;
  topic: string;
  mcq: number;
  truefalse: number;
  written: number;
  difficulty: string;
  language: string;
}): string {
  const s = [
    input.guestId,
    input.topic.trim().toLowerCase(),
    input.mcq,
    input.truefalse,
    input.written,
    input.difficulty,
    input.language,
  ].join("::");
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return `exam_${(h >>> 0).toString(36)}`;
}
