/**
 * USTAD AI — real PWA layer.
 *
 * One registrar, one service worker (`/sw.js`, generated by vite-plugin-pwa),
 * one install-prompt store. Nothing here fakes an install or an installed
 * state: everything is derived from real browser APIs.
 */

export type InstallState =
  | "installed" // running as / detected as an installed app
  | "available" // browser gave us a real beforeinstallprompt
  | "manual" // browser supports install but not programmatically (iOS Safari)
  | "dismissed" // user dismissed the real prompt in this session
  | "unsupported" // no install capability in this browser/context
  | "unknown";

export type PwaSnapshot = {
  state: InstallState;
  standalone: boolean;
  canPrompt: boolean;
  /** Platform hint used to render honest manual instructions. */
  platform: "ios" | "android" | "desktop" | "unknown";
};

type BeforeInstallPromptEvent = Event & {
  prompt: () => Promise<void>;
  userChoice: Promise<{ outcome: "accepted" | "dismissed" }>;
};

let deferred: BeforeInstallPromptEvent | null = null;
let snap: PwaSnapshot = {
  state: "unknown",
  standalone: false,
  canPrompt: false,
  platform: "unknown",
};
const listeners = new Set<(s: PwaSnapshot) => void>();
let wired = false;

function publish(patch: Partial<PwaSnapshot>) {
  snap = { ...snap, ...patch };
  listeners.forEach((l) => l(snap));
}

export function getPwaSnapshot(): PwaSnapshot {
  return snap;
}

export function subscribePwa(fn: (s: PwaSnapshot) => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}

function detectPlatform(): PwaSnapshot["platform"] {
  const ua = navigator.userAgent;
  if (/iPad|iPhone|iPod/.test(ua) || (navigator.maxTouchPoints > 1 && /Macintosh/.test(ua)))
    return "ios";
  if (/Android/i.test(ua)) return "android";
  return "desktop";
}

export function isStandalone(): boolean {
  if (typeof window === "undefined") return false;
  const mq = window.matchMedia?.("(display-mode: standalone)").matches ?? false;
  const mqMinimal = window.matchMedia?.("(display-mode: minimal-ui)").matches ?? false;
  // iOS Safari exposes navigator.standalone instead of display-mode.
  const ios = (navigator as Navigator & { standalone?: boolean }).standalone === true;
  return mq || mqMinimal || ios;
}

async function detectInstalledApps(): Promise<boolean> {
  type WithRelated = Navigator & {
    getInstalledRelatedApps?: () => Promise<unknown[]>;
  };
  const nav = navigator as WithRelated;
  if (typeof nav.getInstalledRelatedApps !== "function") return false;
  try {
    return (await nav.getInstalledRelatedApps()).length > 0;
  } catch {
    return false;
  }
}

function baseState(platform: PwaSnapshot["platform"]): InstallState {
  if (isStandalone()) return "installed";
  if (deferred) return "available";
  // iOS Safari never fires beforeinstallprompt but does support Add to Home Screen.
  if (platform === "ios") return "manual";
  return "unsupported";
}

/** Wire the real browser install events. Safe to call more than once. */
export function initPwa(): void {
  if (typeof window === "undefined" || wired) return;
  wired = true;

  const platform = detectPlatform();
  publish({ platform, standalone: isStandalone(), state: baseState(platform) });

  window.addEventListener("beforeinstallprompt", (event) => {
    event.preventDefault();
    deferred = event as BeforeInstallPromptEvent;
    if (!isStandalone()) publish({ state: "available", canPrompt: true });
  });

  window.addEventListener("appinstalled", () => {
    deferred = null;
    publish({ state: "installed", canPrompt: false });
  });

  const dm = window.matchMedia?.("(display-mode: standalone)");
  dm?.addEventListener?.("change", (e) => {
    publish({ standalone: e.matches, state: e.matches ? "installed" : baseState(platform) });
  });

  void detectInstalledApps().then((installed) => {
    if (installed) publish({ state: "installed", canPrompt: false, standalone: snap.standalone });
  });
}

/**
 * Fire the REAL browser install prompt. Returns the genuine user choice.
 * Never resolves "accepted" without the browser saying so.
 */
export async function promptInstall(): Promise<"accepted" | "dismissed" | "unavailable"> {
  if (!deferred) return "unavailable";
  const event = deferred;
  try {
    await event.prompt();
    const { outcome } = await event.userChoice;
    deferred = null;
    if (outcome === "accepted") {
      // `appinstalled` confirms the real install; keep state honest until then.
      publish({ canPrompt: false });
    } else {
      publish({ state: "dismissed", canPrompt: false });
    }
    return outcome;
  } catch {
    deferred = null;
    publish({ state: baseState(snap.platform), canPrompt: false });
    return "unavailable";
  }
}

/* -------------------- service worker registration -------------------- */

const SW_URL = "/sw.js";

function registrationRefused(): boolean {
  if (typeof window === "undefined") return true;
  if (!("serviceWorker" in navigator)) return true;
  if (!import.meta.env.PROD) return true;
  if (window.self !== window.top) return true;
  const host = window.location.hostname;
  if (host.startsWith("id-preview--") || host.startsWith("preview--")) return true;
  if (host === "lovableproject.com" || host.endsWith(".lovableproject.com")) return true;
  if (host === "lovableproject-dev.com" || host.endsWith(".lovableproject-dev.com")) return true;
  if (host === "beta.lovable.dev" || host.endsWith(".beta.lovable.dev")) return true;
  if (new URLSearchParams(window.location.search).get("sw") === "off") return true;
  return false;
}

async function unregisterAppWorkers() {
  try {
    const regs = await navigator.serviceWorker.getRegistrations();
    await Promise.allSettled(
      regs
        .filter((r) => (r.active?.scriptURL ?? r.installing?.scriptURL ?? "").endsWith(SW_URL))
        .map((r) => r.unregister()),
    );
  } catch {
    /* nothing to clean up */
  }
}

/** Registers the generated service worker in production only. */
export function registerServiceWorker(): void {
  if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;
  if (registrationRefused()) {
    void unregisterAppWorkers();
    return;
  }
  window.addEventListener("load", () => {
    void navigator.serviceWorker.register(SW_URL, { scope: "/" }).catch(() => {
      /* installability simply stays unavailable */
    });
  });
}
